version: 2.1

executors:
  build-executor:
    docker:
      - image: circleci/openjdk:8u212-jdk-stretch
        environment:
          MAVEN_OPTS: -Xmx1g

workflows:
  build:
    jobs:
      - build

jobs:
  build:
    executor: build-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Compile and test
          command: |
            mvn clean install test integration-test
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit

